### ISSUE TITLE
Support for AWS Pinpoint

### ISSUE THREAD

**Issue by lance-anderson** [wp-sms/wp-sms#96]
Any plans to add the AWS Pinpoint service as a gateway?

https://aws.amazon.com/pinpoint/features/engagement-channels/sms/

**Comment by mostafasoufi** [comment]
Hi,

Upon reviewing the document, I will support it in the next release.

**Comment by mostafasoufi** [comment]
Hey,

We recently supported it https://github.com/wp-sms/wp-sms/blob/master/includes/class-wpsms-gateway.php#L99

Best
